### ISSUE TITLE
How to track progress every n seconds

### ISSUE THREAD

**Issue by NicholasAsimov** [playmedia/clappr-ga-events-plugin#4]
This would be a great feature, I would guess you can do this by making such an array knowing the duration of the video but if video is too long the array is going to be big. Is there a better way to do this?

**Comment by kslimani** [comment]
A `progressEachSeconds` _(integer value, 0 as default for disabled)_ could behave same as `progressSeconds` for __VOD__ playback type. The default action value could still be `'progress_' + i + 's'` with `i` as video current position.

And for __LIVE__ playback type also keep same behaviour : use a timer and `i` is duration since __play__ event.
For __LIVE__ with DVR, same but `i` is duration since __play__ or __seek__ event.

What do you think ?

**Comment by NicholasAsimov** [comment]
Sounds good! But for Live with DVR maybe a better thing to do would be to not reset the timer after **seek** so you can track how much total time people watch?

**Comment by kslimani** [comment]
Current behaviour for `progressSeconds, progressSecondsCategory & progressSecondsAction` is :

> If playback type is LIVE, then events are send according time elapsed since play event. If video pause, seek or stop, then events are send again after Nth seconds. (It use a Timer instead of referring to player position)

To keep consistency, maybe add an additional boolean option `resetAfterSeek` (not sure about name) which default to true, and if set to false, does not reset the timer after seek to satisfy total time tracking ?

And also this option could affect "progressSeconds" and "progressEachSeconds" timers. _(or add one option per timer ?)_

**Comment by NicholasAsimov** [comment]
Great idea to have such an option! I would keep it simple for now and have a global option and then if somebody would need control every timer then do that but I think it will not be requested any time soon.

**Comment by kslimani** [comment]
@NicholasAsimov i was thinking about VOD vs LIVE behaviours with `progressEachSeconds` proposal.

* with VOD, the event value is video position in seconds since start
* with LIVE, the event value is video duration in seconds since start (ie play event)

with LIVE, if event value is not reset after a seek event, the value become the total time spent watching live stream and not anymore a "progress" since video start. _(seek event is considered as new watch session by many tracking SDK libraries)_

---

Instead i was thinking about  enhance `progressSeconds` to either accept an Array of integer OR an integer as value. If value is integer, then GA event is sent each N seconds.

So new syntax can still be :

```javascript
gaEventsPlugin: {
  progressSeconds: [3,6,9], // send GA event at 3, 6 and 9 seconds in video progress
}
```

Or be :

```javascript
gaEventsPlugin: {
  progressSeconds: 5, // send GA event each 5 seconds in video progress
}
```

And add a new option to track how much total time people watch a video. Because i think that track video "progress" is different than track "time spent" watching video.

This new feature could use a timer which is enabled when video start and disabled when video stop. With 2 options `resetAfterStop` and `resetAfterSeek` _(defaults to false)_ which indicate if total time is reset after a __stop__ event and/or a __seek__ event.

New feature could be something like _(again, not sure about naming, if you have better idea)_ :

## watchSeconds, watchSecondsCategory & watchSecondsAction

These __optional__ properties are used to track how much time user watch video.

`watchSeconds` __optional__ property is an integer, which is the delay in seconds between each video watch time event sent to Google Analytics. Default value is `0`.

`watchSecondsCategory` __optional__ property is the [eventCategory](https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference#eventCategory) set to send video watch time event. Default value is `undefined`, which default to `eventCategory` plugin option value.

`watchSecondsAction` __optional__ property is a Function which return the [eventAction](https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference#eventAction) set to send video watch time event. Default value is `function(i) { return 'watch_' + i + 's' }`, where `i` argument is the video watch time value in seconds.

```javascript
  /* [...] */
  gaEventsPlugin: {
    trackingId: 'UA-XXXX-Y',
    watchSeconds: 5,
    watchSecondsCategory: 'Watch time', // default is 'Video'
    watchSecondsAction: function(i) { return i + ' seconds' },
  }
  /* [...] */
```

## resetWatchAfterSeek and resetWatchAfterStop

`resetWatchAfterSeek` and `resetWatchAfterStop` __optional__ properties are boolean which respectively indicate if video watch time duration is reset after a __seek__ and/or a __stop__ event.

Default value for these two properties is `false`. _(adjust to your needs)_

These options must be used with `watchSeconds`, otherwise are ignored.
